### ISSUE TITLE
Argoverse 2 Motion Forecasting Dataset 

### ISSUE THREAD

**Issue by EvergreenChang** [zhejz/HPTR#3]
I am using pack_h5_av2.py to process AV2's training data, and I get the following error:

Traceback (most recent call last):
  File "/workspace/HPTR/src/pack_h5_av2.py", line 342, in <module>
    main()
  File "/workspace/HPTR/src/pack_h5_av2.py", line 270, in main
    pack_utils.repack_episode_agents(
  File "/workspace/HPTR/./src/utils/pack_h5.py", line 783, in repack_episode_agents
    episode_reduced["agent/dest"][i] = find_dest(
  File "/workspace/HPTR/./src/utils/pack_h5.py", line 836, in find_dest
    dest_map_id, next_map_id = map_edge[np.random.choice(next_edges)]
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

It seems that a null value is being created, how can I solve this problem?

**Comment by zhejz** [comment]
I haven't encountered this problem before, but for this repo `agent/dest` is actually not used. You can simply set it to some dummy value and remove the call of `find_dest`.

**Comment by EvergreenChang** [comment]
Thanks for the answer! I've added a loop to judge nulls and it works.
