### ISSUE TITLE
Validation on AV2

### ISSUE THREAD

**Issue by jakubmoscinski** [zhejz/HPTR#6]
During validation I encountered the following problem:

```
Traceback (most recent call last):
  File "/root/autodl-tmp/HPTR-main/src/run.py", line 60, in main
    trainer.validate(model=model, datamodule=datamodule)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 821, in validate
    return self._call_and_handle_interrupt(self._validate_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _validate_impl
    results = self._run(model, ckpt_path=self.validated_ckpt_path)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_evaluating(self)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 206, in start_evaluating
    self._results = trainer.run_stage()
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in run_stage
    return self._run_evaluate()
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1334, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/HPTR-main/src/run.py", line 60, in main
    trainer.validate(model=model, datamodule=datamodule)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 821, in validate
    return self._call_and_handle_interrupt(self._validate_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _validate_impl
    results = self._run(model, ckpt_path=self.validated_ckpt_path)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 239, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_evaluating(self)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 447, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 206, in start_evaluating
    self._results = trainer.run_stage()
  File "/root/autodl-tmp/HPTR-main/src/pl_modules/waymo_motion.py", line 130, in validation_step
    self._save_to_submission_files(pred_dict, batch)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in run_stage
    return self._run_evaluate()
  File "/root/autodl-tmp/HPTR-main/src/pl_modules/waymo_motion.py", line 311, in _save_to_submission_files
    self.sub_av2.add_to_submissions(**submission_kargs_dict)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1334, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/root/autodl-tmp/HPTR-main/src/utils/submission.py", line 176, in add_to_submissions
    waymo_trajs = torch_pos2global(
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/HPTR-main/src/utils/transform_utils.py", line 171, in torch_pos2global
    return torch.matmul(in_pos, local_rot.transpose(-1, -2)) + local_pos
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
RuntimeError: expected scalar type Double but found Float
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 239, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
  File "/root/autodl-tmp/miniconda3/envs/hptr/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 447, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/root/autodl-tmp/HPTR-main/src/pl_modules/waymo_motion.py", line 130, in validation_step
    self._save_to_submission_files(pred_dict, batch)
  File "/root/autodl-tmp/HPTR-main/src/pl_modules/waymo_motion.py", line 311, in _save_to_submission_files
    self.sub_av2.add_to_submissions(**submission_kargs_dict)
  File "/root/autodl-tmp/HPTR-main/src/utils/submission.py", line 176, in add_to_submissions
    waymo_trajs = torch_pos2global(
  File "/root/autodl-tmp/HPTR-main/src/utils/transform_utils.py", line 171, in torch_pos2global
    return torch.matmul(in_pos, local_rot.transpose(-1, -2)) + local_pos
RuntimeError: expected scalar type Double but found Float
```

**Comment by roydenwa** [comment]
@jakubmoscinski @zhejz I had the same issue. I opened a [PR](https://github.com/zhejz/HPTR/pull/7) for my fix.

**Comment by jakubmoscinski** [comment]
I have discovered that the explicit casting solves the problem some time ago. Forgotten to close the issue.

Many thanks anyway!
